/* ===========================================================================
   forecast.js

   A browser-side reimplementation of the feature engineering and the four
   exported models from earthquake_analysis.py, including the fault-distance
   features derived from the nearest active fault.

   This file is a second implementation of maths that already exists in Python,
   which is a standing hazard: if the two drift apart the page will quietly
   report wrong forecasts and nothing will complain. That is what
   verify_bundle.cjs is for. It replays the verification vectors baked into
   model_bundle.json through this exact code and fails on any disagreement past
   1e-6. Change anything here and run it.

   Loaded as a plain script in the browser (sets window.Forecast) and required
   directly by the verifier in Node.
   =========================================================================== */
(function (root, factory) {
  if (typeof module === "object" && module.exports) { module.exports = factory(); }
  else { root.Forecast = factory(); }
}(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  var LOG10E = Math.log10(Math.E);
  var EARTH_RADIUS_KM = 6371.0088;

  /* --- small numeric helpers, matching NumPy semantics ------------------- */

  function sum(a) { var s = 0; for (var i = 0; i < a.length; i++) { s += a[i]; } return s; }
  function mean(a) { return a.length ? sum(a) / a.length : NaN; }

  /** Sample variance with ddof=1, as NumPy's var(ddof=1). */
  function variance(a) {
    if (a.length < 2) { return 0; }
    var m = mean(a), s = 0;
    for (var i = 0; i < a.length; i++) { s += (a[i] - m) * (a[i] - m); }
    return s / (a.length - 1);
  }

  /** First index of the maximum, as NumPy's argmax. */
  function argmax(a) {
    var best = 0;
    for (var i = 1; i < a.length; i++) { if (a[i] > a[best]) { best = i; } }
    return best;
  }

  /**
   * Bin counts over explicit edges, matching np.histogram: every bin is
   * half-open [lo, hi) except the last, which is closed at both ends.
   */
  function histogram(values, edges) {
    var counts = new Array(edges.length - 1).fill(0);
    for (var i = 0; i < values.length; i++) {
      var v = values[i];
      if (v < edges[0] || v > edges[edges.length - 1]) { continue; }
      if (v === edges[edges.length - 1]) { counts[counts.length - 1] += 1; continue; }
      var lo = 0, hi = edges.length - 1;
      while (lo < hi - 1) {
        var mid = (lo + hi) >> 1;
        if (v >= edges[mid]) { lo = mid; } else { hi = mid; }
      }
      counts[lo] += 1;
    }
    return counts;
  }

  function round5(x) { return Math.round(x * 1e5) / 1e5; }

  function haversineKm(lat1, lon1, lat2, lon2) {
    var toRad = Math.PI / 180;
    var dLat = (lat2 - lat1) * toRad, dLon = (lon2 - lon1) * toRad;
    var a = Math.sin(dLat / 2) * Math.sin(dLat / 2)
      + Math.cos(lat1 * toRad) * Math.cos(lat2 * toRad)
      * Math.sin(dLon / 2) * Math.sin(dLon / 2);
    return 2 * EARTH_RADIUS_KM * Math.asin(Math.sqrt(Math.min(Math.max(a, 0), 1)));
  }

  /* --- frequency magnitude distribution ---------------------------------- */

  /**
   * Returns {bins, inc, cum}. Bin edges are generated by index rather than by
   * accumulating a float step, so the result matches np.arange rounded to five
   * decimals instead of drifting by an ulp per bin.
   */
  function fmd(mags, binWidth) {
    var finite = mags.filter(function (m) { return isFinite(m); });
    if (!finite.length) { return { bins: [], inc: [], cum: [] }; }
    var min = Math.min.apply(null, finite), max = Math.max.apply(null, finite);
    var lo = Math.floor(min / binWidth) * binWidth;
    var hi = Math.ceil(max / binWidth) * binWidth;
    var count = Math.round((hi - lo) / binWidth) + 1;
    var bins = [];
    for (var i = 0; i < count; i++) { bins.push(round5(lo + i * binWidth)); }

    var edges = bins.map(function (b) { return b - binWidth / 2; });
    edges.push(bins[bins.length - 1] + binWidth / 2);
    var inc = histogram(finite, edges);

    var cum = new Array(inc.length).fill(0);
    var running = 0;
    for (var j = inc.length - 1; j >= 0; j--) { running += inc[j]; cum[j] = running; }
    return { bins: bins, inc: inc, cum: cum };
  }

  function mcMaxc(mags, binWidth) {
    var d = fmd(mags, binWidth);
    if (!d.bins.length) { return NaN; }
    return d.bins[argmax(d.inc)] + 0.2;
  }

  /** Aki-Utsu maximum likelihood b, with the Shi and Bolt standard error. */
  function bValueMle(mags, mc, binWidth) {
    var m = mags.filter(function (v) { return isFinite(v) && v >= mc - binWidth / 2; });
    if (m.length < 2) { return { b: NaN, bSe: NaN, a: NaN, n: m.length }; }
    var mu = mean(m);
    var denom = mu - (mc - binWidth / 2);
    var b = denom > 0 ? LOG10E / denom : NaN;
    var ss = 0;
    for (var i = 0; i < m.length; i++) { ss += (m[i] - mu) * (m[i] - mu); }
    var bSe = 2.30 * b * b * Math.sqrt(ss / (m.length * (m.length - 1)));
    return { b: b, bSe: bSe, a: Math.log10(m.length) + b * mc, n: m.length };
  }

  /** Least squares fit of log10 N(>=M) = a - b*M above Mc. */
  function bValueLsq(mags, mc, binWidth) {
    var empty = { b: NaN, bSe: NaN, a: NaN, n: 0, stdGr: NaN };
    var d = fmd(mags, binWidth);
    if (!d.bins.length) { return empty; }
    var x = [], y = [];
    for (var i = 0; i < d.bins.length; i++) {
      if (d.bins[i] >= mc - binWidth / 2 && d.cum[i] > 0) {
        x.push(d.bins[i]);
        y.push(Math.log10(d.cum[i]));
      }
    }
    if (x.length < 3) { return { b: NaN, bSe: NaN, a: NaN, n: x.length, stdGr: NaN }; }
    var xb = mean(x), yb = mean(y), sxx = 0, sxy = 0;
    for (var j = 0; j < x.length; j++) {
      sxx += (x[j] - xb) * (x[j] - xb);
      sxy += (x[j] - xb) * (y[j] - yb);
    }
    var slope = sxy / sxx, intercept = yb - slope * xb;
    var ssRes = 0;
    for (var k = 0; k < x.length; k++) {
      var r = y[k] - (intercept + slope * x[k]);
      ssRes += r * r;
    }
    return {
      b: -slope, a: intercept, n: x.length,
      bSe: Math.sqrt(ssRes / (x.length - 2) / sxx),
      stdGr: Math.sqrt(ssRes / (x.length - 1)),
    };
  }

  /** RMS departure of the observed cumulative FMD from a fitted GR line. */
  function grDeviation(mags, a, b, binWidth) {
    if (!isFinite(a) || !isFinite(b)) { return NaN; }
    var d = fmd(mags, binWidth);
    var resid = [], kept = 0;
    for (var i = 0; i < d.bins.length; i++) {
      if (d.cum[i] > 0) {
        kept += 1;
        resid.push(Math.log10(d.cum[i]) - (a - b * d.bins[i]));
      }
    }
    if (kept < 2) { return NaN; }
    var ss = 0;
    for (var j = 0; j < resid.length; j++) { ss += resid[j] * resid[j]; }
    return Math.sqrt(ss / (kept - 1));
  }

  function energy(mags, coeffs) {
    var c0 = coeffs[0], c1 = coeffs[1];
    var exps = mags.map(function (m) { return c0 + c1 * m; });
    var peak = Math.max.apply(null, exps);
    var acc = 0;
    for (var i = 0; i < exps.length; i++) { acc += Math.pow(10, exps[i] - peak); }
    return Math.pow(10, (peak + Math.log10(acc)) / 2);
  }

  /** Habermann z: change in daily rate between the halves of the window. */
  function zValue(times, tStart, tEnd) {
    var mid = (tStart + tEnd) / 2;
    var halves = [[tStart, mid], [mid, tEnd]];
    var out = [];
    for (var h = 0; h < 2; h++) {
      var lo = halves[h][0], hi = halves[h][1];
      var days = Math.max(Math.round(hi - lo), 1);
      var edges = [];
      for (var i = 0; i <= days; i++) { edges.push(lo + (hi - lo) * i / days); }
      var counts = histogram(times, edges);
      out.push({ r: mean(counts), s: counts.length > 1 ? variance(counts) : 0, n: counts.length });
    }
    var denom = Math.sqrt(out[0].s / Math.max(out[0].n, 1) + out[1].s / Math.max(out[1].n, 1));
    return denom > 0 ? (out[0].r - out[1].r) / denom : 0;
  }

  function betaValue(nWindow, nBackground, delta) {
    var denom = Math.sqrt(nBackground * delta * (1 - delta));
    return denom > 0 ? (nWindow - nBackground * delta) / denom : 0;
  }

  /**
   * Distance to the nearest active fault, in km.
   *
   * The catalogue was measured against fault lines mapped in QGIS, which this
   * page cannot rerun, so the bundle ships the distinct source points those
   * measurements resolved to and the nearest one is taken. Checked against the
   * supplied column on 3,000 catalogue events: the same source is chosen for
   * 99.7% of them, and the rest sit at most 0.24 km further out.
   */
  function nearestSourceKm(lat, lon, sources) {
    if (!sources || !sources.lat || !sources.lat.length) { return NaN; }
    var best = Infinity;
    for (var i = 0; i < sources.lat.length; i++) {
      var d = haversineKm(lat, lon, sources.lat[i], sources.lon[i]);
      if (d < best) { best = d; }
    }
    return best;
  }

  /**
   * Fault-distance statistics for one window, mirroring _fault_features in
   * earthquake_analysis.py. Weighted by released energy, so one large
   * foreshock pulls the summary toward its own distance.
   */
  function faultFeatures(dists, mags, times) {
    var n = dists.length;
    var out = { Dist_min: NaN, Dist_mean: NaN, Dist_std: NaN, Dist_wmean: NaN, Dist_trend: NaN };
    if (!n) { return out; }
    var weights = mags.map(function (m) { return Math.pow(10, 1.5 * m); });
    var total = sum(weights);
    var wsum = 0;
    for (var i = 0; i < n; i++) { wsum += weights[i] * dists[i]; }

    var trend = 0;
    var spread = Math.max.apply(null, times) - Math.min.apply(null, times);
    if (n >= 3 && spread > 0) {
      var tb = mean(times), db = mean(dists), stt = 0, std = 0;
      for (var j = 0; j < n; j++) { stt += (times[j] - tb) * (times[j] - tb); std += (times[j] - tb) * (dists[j] - db); }
      trend = stt > 0 ? std / stt : 0;
    }
    out.Dist_min = Math.min.apply(null, dists);
    out.Dist_mean = mean(dists);
    out.Dist_std = n > 1 ? Math.sqrt(variance(dists)) : 0;
    out.Dist_wmean = total > 0 ? wsum / total : mean(dists);
    out.Dist_trend = trend;
    return out;
  }

  /* --- the engineered features -------------------------------------------- */

  /**
   * Build the feature vector for one observation window.
   *
   * `events` are the catalogued events inside the window, each
   * {before, mag, lat, lon, depth} where `before` is days before the target
   * time. `context` supplies the regional history the window cannot see:
   * {priorTimes, priorMags, backgroundCount, span, tEnd}.
   */
  function buildFeatures(events, context, cfg) {
    var bw = cfg.mag_bin;
    var mags = events.map(function (e) { return e.mag; });
    var times = events.map(function (e) { return context.tEnd - e.before; });
    var tEnd = context.tEnd;
    var tStart = tEnd - cfg.window_days;

    var n = mags.length;
    var magMax = Math.max.apply(null, mags);
    var magMean = mean(mags);
    var mc = n >= 5 ? mcMaxc(mags, bw) : Math.min.apply(null, mags);
    var lsq = bValueLsq(mags, mc, bw);
    var mle = bValueMle(mags, mc, bw);

    var ss = 0;
    for (var i = 0; i < n; i++) { ss += (mags[i] - magMean) * (mags[i] - magMean); }
    var spread = n > 1 ? Math.sqrt(ss / (n * (n - 1))) : NaN;

    var values = {
      NO: n,
      Mag_max: magMax,
      Mag_mean: magMean,
      b_lsq: lsq.b,
      a_lsq: lsq.a,
      b_std_lsq: isFinite(lsq.b) ? 2.3 * lsq.b * lsq.b * spread : NaN,
      std_gr_lsq: lsq.stdGr,
      b_mlk: mle.b,
      a_mlk: mle.a,
      b_std_mlk: isFinite(mle.b) ? 2.3 * mle.b * mle.b * spread : NaN,
      std_gr_mlk: grDeviation(mags, mle.a, mle.b, bw),
      dM_lsq: (isFinite(lsq.b) && lsq.b !== 0) ? magMax - lsq.a / lsq.b : NaN,
      dM_mlk: (isFinite(mle.b) && mle.b !== 0) ? magMax - mle.a / mle.b : NaN,
      Energy: energy(mags, cfg.energy_coeffs),
      x7_lsq: isFinite(lsq.b) ? Math.pow(10, -3 * lsq.b) : NaN,
      x7_mlk: isFinite(mle.b) ? Math.pow(10, -3 * mle.b) : NaN,
      zvalue: zValue(times, tStart, tEnd),
      beta: betaValue(n, Math.max(context.backgroundCount, 1),
                      cfg.window_days / cfg.background_days),
    };

    /* Fault distance comes from the event when the caller supplies it, which
       keeps the verification vectors exactly comparable to Python, and is
       looked up from the shipped source points otherwise. */
    var dists = events.map(function (e) {
      return (typeof e.dist === "number" && isFinite(e.dist))
        ? e.dist
        : nearestSourceKm(e.lat, e.lon, cfg.sources);
    });
    var faults = faultFeatures(dists, mags, times);
    Object.keys(faults).forEach(function (k) { values[k] = faults[k]; });

    var thresholds = { T_elaps6: 6.0, T_elaps65: 6.5, T_elaps7: 7.0, T_elaps75: 7.5 };
    Object.keys(thresholds).forEach(function (key) {
      var threshold = thresholds[key];
      var last = null;
      for (var j = context.priorTimes.length - 1; j >= 0; j--) {
        if (context.priorMags[j] >= threshold) { last = context.priorTimes[j]; break; }
      }
      values[key] = last === null ? context.span : tEnd - last;
    });

    return cfg.features.map(function (name) { return values[name]; });
  }

  /**
   * Regional context for an epicentre and target time, read from the shipped
   * catalogue. Four features count days since the last large regional event and
   * the beta statistic needs a background rate, so none of this can come from
   * the handful of events a user types in.
   */
  function regionalContext(catalogue, lat, lon, tEnd, cfg) {
    var priorTimes = [], priorMags = [], backgroundCount = 0;
    var backgroundStart = tEnd - cfg.background_days;
    /* The epsilon matters. A mainshock's own catalogue record sits at exactly
       tEnd in Python, but survives a rounding trip as tEnd minus a hair, and
       without the guard the browser reads that record as a large regional
       event moments earlier, collapsing every T_elaps feature to zero. */
    var EPS = 1e-7;
    for (var i = 0; i < catalogue.n; i++) {
      var t = catalogue.t[i];
      if (t >= tEnd - EPS) { break; }
      if (haversineKm(lat, lon, catalogue.lat[i], catalogue.lon[i]) > cfg.radius_km) { continue; }
      priorTimes.push(t);
      priorMags.push(catalogue.mag[i]);
      if (t >= backgroundStart) { backgroundCount += 1; }
    }
    return {
      priorTimes: priorTimes,
      priorMags: priorMags,
      backgroundCount: backgroundCount,
      span: catalogue.t[catalogue.n - 1] - catalogue.t[0],
      tEnd: tEnd,
    };
  }

  /* --- preprocessing, mirroring DataBundle -------------------------------- */

  function preprocess(raw, bundle) {
    var logSet = {};
    bundle.log_features.forEach(function (f) { logSet[f] = true; });
    return raw.map(function (value, i) {
      var name = bundle.features[i];
      var v = value;
      if (logSet[name] && v !== null && isFinite(v)) {
        v = Math.sign(v) * Math.log10(1 + Math.abs(v));
      }
      if (v === null || !isFinite(v)) { v = bundle.median[i]; }
      return Math.min(Math.max(v, bundle.winsor_lo[i]), bundle.winsor_hi[i]);
    });
  }

  /* --- model runners ------------------------------------------------------ */

  function runTree(tree, x) {
    var node = 0;
    while (tree.l[node] !== -1) {
      node = x[tree.f[node]] <= tree.t[node] ? tree.l[node] : tree.r[node];
    }
    return tree.v[node];
  }

  function predictFeatures(model, x) {
    var i, acc = 0;
    if (model.kind === "forest") {
      for (i = 0; i < model.trees.length; i++) { acc += runTree(model.trees[i], x); }
      return acc / model.trees.length;
    }
    if (model.kind === "boosted") {
      acc = model.init;
      for (i = 0; i < model.trees.length; i++) { acc += model.lr * runTree(model.trees[i], x); }
      return acc;
    }
    if (model.kind === "linear") {
      acc = model.intercept;
      for (i = 0; i < x.length; i++) {
        acc += model.coef[i] * ((x[i] - model.mean[i]) / model.scale[i]);
      }
      return acc;
    }
    throw new Error("Not a feature model: " + model.kind);
  }

  function sigmoid(x) { return 1 / (1 + Math.exp(-Math.max(-60, Math.min(60, x)))); }

  /**
   * Build the LSTM's input tensor: the last seq_len events as
   * [magnitude, depth, hours since the previous event, dLat, dLon],
   * left-padded with zeros, then log-transformed, clipped and standardised
   * exactly as DataBundle.sequence does.
   */
  function buildSequence(events, lat, lon, model) {
    var L = model.seq_len, C = 5;
    var tensor = [];
    var i;
    for (i = 0; i < L; i++) { tensor.push([0, 0, 0, 0, 0]); }

    var taken = events.slice(Math.max(0, events.length - L));
    if (taken.length) {
      var times = taken.map(function (e) { return -e.before; });
      for (i = 0; i < taken.length; i++) {
        var gapHours = (i === 0 ? 0 : (times[i] - times[i - 1])) * 24;
        tensor[L - taken.length + i] = [
          taken[i].mag, taken[i].depth, gapHours,
          taken[i].lat - lat, taken[i].lon - lon,
        ];
      }
    }
    for (i = 0; i < L; i++) {
      var g = Math.max(tensor[i][2], 0);
      tensor[i][2] = Math.log1p(g);
      for (var c = 0; c < C; c++) {
        var v = Math.min(Math.max(tensor[i][c], model.seq_lo[c]), model.seq_hi[c]);
        tensor[i][c] = (v - model.seq_mean[c]) / model.seq_scale[c];
      }
    }
    return tensor;
  }

  function predictLstm(model, tensor) {
    var H = model.units, F = 5;
    var h = new Array(H).fill(0), c = new Array(H).fill(0);
    for (var step = 0; step < tensor.length; step++) {
      var z = tensor[step].concat(h);
      var gates = new Array(4 * H).fill(0);
      for (var g = 0; g < 4 * H; g++) {
        var acc = model.b[g];
        for (var k = 0; k < F + H; k++) { acc += z[k] * model.W[k][g]; }
        gates[g] = acc;
      }
      for (var u = 0; u < H; u++) {
        var i_ = sigmoid(gates[u]);
        var f_ = sigmoid(gates[H + u]);
        var o_ = sigmoid(gates[2 * H + u]);
        var g_ = Math.tanh(gates[3 * H + u]);
        c[u] = f_ * c[u] + i_ * g_;
        h[u] = o_ * Math.tanh(c[u]);
      }
    }
    var out = model.by;
    for (var j = 0; j < H; j++) { out += h[j] * model.Wy[j]; }
    return out;
  }

  /* --- public surface ----------------------------------------------------- */

  /**
   * Full pipeline for one window: raw events in, forecast out.
   * Returns {magnitude, features, raw} so a caller can show the working.
   */
  function forecast(opts) {
    var bundle = opts.bundle;
    var model = bundle.models[opts.model];
    var events = opts.events.slice().sort(function (a, b) { return b.before - a.before; });

    if (model.input === "sequence") {
      var tensor = buildSequence(events, opts.lat, opts.lon, model);
      return { magnitude: predictLstm(model, tensor), features: null, raw: null };
    }
    var raw = opts.features || buildFeatures(events, opts.context, bundle);
    var x = preprocess(raw, bundle);
    return { magnitude: predictFeatures(model, x), features: x, raw: raw };
  }

  return {
    fmd: fmd,
    nearestSourceKm: nearestSourceKm,
    faultFeatures: faultFeatures,
    mcMaxc: mcMaxc,
    bValueMle: bValueMle,
    bValueLsq: bValueLsq,
    energy: energy,
    zValue: zValue,
    haversineKm: haversineKm,
    buildFeatures: buildFeatures,
    regionalContext: regionalContext,
    preprocess: preprocess,
    buildSequence: buildSequence,
    predictFeatures: predictFeatures,
    predictLstm: predictLstm,
    forecast: forecast,
  };
}));
